import type { Tender } from "./types";

export const MOCK_TENDERS: Tender[] = [
  {
    id: "TND-2026-001",
    title: {
      en: "Highway Infrastructure Modernization — Casablanca-Rabat Corridor",
      ar: "تحديث البنية التحتية للطريق السريع — محور الدار البيضاء-الرباط",
      fr: "Modernisation de l'infrastructure autoroutière — Corridor Casablanca-Rabat",
    },
    organization: {
      en: "Ministry of Equipment and Water — Morocco",
      ar: "وزارة التجهيز والماء — المغرب",
      fr: "Ministère de l'Équipement et de l'Eau — Maroc",
    },
    country: "Morocco",
    countryCode: "MA",
    sector: "construction",
    budget: 45000000,
    currency: "MAD",
    deadline: "2026-04-15",
    publishDate: "2026-02-28",
    status: "open",
    description: {
      en: "Major infrastructure project to modernize the 90km highway corridor between Casablanca and Rabat. Includes road resurfacing, bridge reinforcement, smart traffic management systems, and toll booth modernization. The project aims to reduce travel time and improve safety standards.",
      ar: "مشروع بنية تحتية كبير لتحديث ممر الطريق السريع بطول 90 كم بين الدار البيضاء والرباط. يشمل إعادة تسطيح الطريق وتعزيز الجسور وأنظمة إدارة المرور الذكية وتحديث أكشاك الرسوم.",
      fr: "Projet majeur d'infrastructure pour moderniser le corridor autoroutier de 90 km entre Casablanca et Rabat. Comprend le resurfaçage routier, le renforcement des ponts, les systèmes de gestion intelligente du trafic.",
    },
    requirements: ["ISO 9001", "10+ years experience", "Previous government contracts", "Financial guarantee"],
    matchScore: 92,
  },
  {
    id: "TND-2026-002",
    title: {
      en: "NEOM Smart City — IT Infrastructure Phase 3",
      ar: "مدينة نيوم الذكية — البنية التحتية لتكنولوجيا المعلومات المرحلة 3",
      fr: "NEOM Ville Intelligente — Infrastructure IT Phase 3",
    },
    organization: {
      en: "NEOM Company — Saudi Arabia",
      ar: "شركة نيوم — المملكة العربية السعودية",
      fr: "Société NEOM — Arabie saoudite",
    },
    country: "Saudi Arabia",
    countryCode: "SA",
    sector: "it",
    budget: 120000000,
    currency: "SAR",
    deadline: "2026-05-01",
    publishDate: "2026-03-01",
    status: "open",
    description: {
      en: "Phase 3 of NEOM's IT infrastructure deployment covering cloud computing centers, 5G network expansion, IoT sensor networks, and AI-powered city management platforms. Requires cutting-edge technology integration and smart city expertise.",
      ar: "المرحلة الثالثة من نشر البنية التحتية لتكنولوجيا المعلومات في نيوم تشمل مراكز الحوسبة السحابية وتوسيع شبكة 5G وشبكات مستشعرات إنترنت الأشياء ومنصات إدارة المدينة بالذكاء الاصطناعي.",
      fr: "Phase 3 du déploiement de l'infrastructure IT de NEOM couvrant les centres de cloud computing, l'expansion du réseau 5G, les réseaux de capteurs IoT et les plateformes de gestion de ville alimentées par l'IA.",
    },
    requirements: ["Smart city experience", "Cloud certifications", "5G deployment experience", "Security clearance"],
    matchScore: 78,
  },
  {
    id: "TND-2026-003",
    title: {
      en: "Dubai Municipality — Smart Waste Management System",
      ar: "بلدية دبي — نظام إدارة النفايات الذكي",
      fr: "Municipalité de Dubaï — Système intelligent de gestion des déchets",
    },
    organization: {
      en: "Dubai Municipality — UAE",
      ar: "بلدية دبي — الإمارات",
      fr: "Municipalité de Dubaï — EAU",
    },
    country: "UAE",
    countryCode: "AE",
    sector: "it",
    budget: 35000000,
    currency: "AED",
    deadline: "2026-03-25",
    publishDate: "2026-02-10",
    status: "closing-soon",
    description: {
      en: "Implementation of a city-wide smart waste management system using IoT sensors, route optimization AI, and a citizen reporting platform. Includes 10,000 smart bins, fleet management for 500+ vehicles, and a centralized monitoring dashboard.",
      ar: "تنفيذ نظام إدارة نفايات ذكي على مستوى المدينة باستخدام مستشعرات إنترنت الأشياء والذكاء الاصطناعي لتحسين المسارات ومنصة إبلاغ المواطنين.",
      fr: "Mise en œuvre d'un système de gestion intelligente des déchets à l'échelle de la ville utilisant des capteurs IoT, l'IA d'optimisation des itinéraires et une plateforme de signalement citoyen.",
    },
    requirements: ["IoT expertise", "Fleet management", "Mobile app development", "UAE trade license"],
    matchScore: 85,
  },
  {
    id: "TND-2026-004",
    title: {
      en: "New Administrative Capital — Hospital Equipment Supply",
      ar: "العاصمة الإدارية الجديدة — توريد معدات المستشفيات",
      fr: "Nouvelle Capitale Administrative — Fourniture d'équipements hospitaliers",
    },
    organization: {
      en: "Ministry of Health — Egypt",
      ar: "وزارة الصحة — مصر",
      fr: "Ministère de la Santé — Égypte",
    },
    country: "Egypt",
    countryCode: "EG",
    sector: "healthcare",
    budget: 85000000,
    currency: "EGP",
    deadline: "2026-04-30",
    publishDate: "2026-03-05",
    status: "open",
    description: {
      en: "Supply and installation of medical equipment for 3 new hospitals in Egypt's New Administrative Capital. Includes MRI machines, CT scanners, surgical robots, laboratory equipment, and a unified hospital information system.",
      ar: "توريد وتركيب المعدات الطبية لـ 3 مستشفيات جديدة في العاصمة الإدارية الجديدة بمصر. يشمل أجهزة الرنين المغناطيسي والتصوير المقطعي والروبوتات الجراحية ومعدات المختبرات.",
      fr: "Fourniture et installation d'équipements médicaux pour 3 nouveaux hôpitaux dans la Nouvelle Capitale Administrative d'Égypte.",
    },
    requirements: ["Medical device certifications", "FDA/CE marking", "Installation experience", "Training services"],
    matchScore: 65,
  },
  {
    id: "TND-2026-005",
    title: {
      en: "Solar Power Plant — Ouarzazate Phase IV",
      ar: "محطة الطاقة الشمسية — ورزازات المرحلة الرابعة",
      fr: "Centrale solaire — Ouarzazate Phase IV",
    },
    organization: {
      en: "MASEN — Morocco",
      ar: "الوكالة المغربية للطاقة المستدامة — المغرب",
      fr: "MASEN — Maroc",
    },
    country: "Morocco",
    countryCode: "MA",
    sector: "energy",
    budget: 200000000,
    currency: "MAD",
    deadline: "2026-06-01",
    publishDate: "2026-03-01",
    status: "open",
    description: {
      en: "Construction of a 200MW concentrated solar power plant as Phase IV of the Noor-Ouarzazate complex. Includes CSP tower technology, molten salt storage system, and grid connection infrastructure. Part of Morocco's target to reach 52% renewable energy by 2030.",
      ar: "بناء محطة طاقة شمسية مركزة بقدرة 200 ميغاواط كمرحلة رابعة من مجمع نور-ورزازات. يشمل تقنية برج CSP ونظام تخزين الملح المنصهر والبنية التحتية لتوصيل الشبكة.",
      fr: "Construction d'une centrale solaire concentrée de 200 MW dans le cadre de la Phase IV du complexe Noor-Ouarzazate.",
    },
    requirements: ["CSP technology experience", "EPC contractor", "Environmental impact assessment", "Grid integration"],
    matchScore: 71,
  },
  {
    id: "TND-2026-006",
    title: {
      en: "Kuwait Oil Company — Pipeline Monitoring System",
      ar: "شركة نفط الكويت — نظام مراقبة خطوط الأنابيب",
      fr: "Kuwait Oil Company — Système de surveillance des pipelines",
    },
    organization: {
      en: "Kuwait Oil Company — Kuwait",
      ar: "شركة نفط الكويت — الكويت",
      fr: "Kuwait Oil Company — Koweït",
    },
    country: "Kuwait",
    countryCode: "KW",
    sector: "energy",
    budget: 18000000,
    currency: "KWD",
    deadline: "2026-04-20",
    publishDate: "2026-02-20",
    status: "open",
    description: {
      en: "Design and implementation of an AI-powered pipeline monitoring and leak detection system across 2,500km of oil and gas pipelines. Includes drone surveillance integration, fiber optic sensing, and a real-time monitoring center.",
      ar: "تصميم وتنفيذ نظام مراقبة خطوط الأنابيب وكشف التسرب بالذكاء الاصطناعي عبر 2500 كم من خطوط أنابيب النفط والغاز.",
      fr: "Conception et mise en œuvre d'un système de surveillance des pipelines et de détection de fuites alimenté par l'IA sur 2 500 km de pipelines pétroliers et gaziers.",
    },
    requirements: ["Oil & gas experience", "SCADA systems", "Drone operations license", "Safety certifications"],
    matchScore: 58,
  },
  {
    id: "TND-2026-007",
    title: {
      en: "Qatar Foundation — E-Learning Platform Development",
      ar: "مؤسسة قطر — تطوير منصة التعليم الإلكتروني",
      fr: "Fondation Qatar — Développement de plateforme e-learning",
    },
    organization: {
      en: "Qatar Foundation — Qatar",
      ar: "مؤسسة قطر — قطر",
      fr: "Fondation Qatar — Qatar",
    },
    country: "Qatar",
    countryCode: "QA",
    sector: "education",
    budget: 25000000,
    currency: "QAR",
    deadline: "2026-05-15",
    publishDate: "2026-03-08",
    status: "open",
    description: {
      en: "Development of a comprehensive bilingual (Arabic-English) e-learning platform for K-12 education. Features include AI-powered personalized learning paths, virtual classrooms, AR/VR educational content, parent dashboards, and integration with national curriculum standards.",
      ar: "تطوير منصة تعليم إلكتروني شاملة ثنائية اللغة (عربي-إنجليزي) للتعليم من الروضة حتى الثانوية. تشمل مسارات تعلم مخصصة بالذكاء الاصطناعي وفصول افتراضية ومحتوى تعليمي بالواقع المعزز والافتراضي.",
      fr: "Développement d'une plateforme e-learning bilingue complète (arabe-anglais) pour l'éducation K-12.",
    },
    requirements: ["EdTech experience", "Arabic content creation", "LMS development", "Accessibility compliance"],
    matchScore: 88,
  },
  {
    id: "TND-2026-008",
    title: {
      en: "Algiers Metro Extension — Line 2 Construction",
      ar: "توسيع مترو الجزائر — بناء الخط 2",
      fr: "Extension du Métro d'Alger — Construction de la Ligne 2",
    },
    organization: {
      en: "Ministry of Transport — Algeria",
      ar: "وزارة النقل — الجزائر",
      fr: "Ministère des Transports — Algérie",
    },
    country: "Algeria",
    countryCode: "DZ",
    sector: "transport",
    budget: 95000000000,
    currency: "DZD",
    deadline: "2026-07-01",
    publishDate: "2026-03-01",
    status: "open",
    description: {
      en: "Construction of Line 2 of the Algiers Metro system, spanning 18km with 15 stations. Includes tunnel boring, station construction, signaling systems, rolling stock procurement, and depot facilities.",
      ar: "بناء الخط 2 من شبكة مترو الجزائر بطول 18 كم و15 محطة. يشمل حفر الأنفاق وبناء المحطات وأنظمة الإشارات وشراء القطارات ومرافق المستودعات.",
      fr: "Construction de la Ligne 2 du Métro d'Alger, s'étendant sur 18 km avec 15 stations.",
    },
    requirements: ["Metro construction experience", "TBM operations", "Railway signaling", "Consortium acceptable"],
    matchScore: 45,
  },
  {
    id: "TND-2026-009",
    title: {
      en: "Oman Water Desalination Plant — Barka 5",
      ar: "محطة تحلية المياه في عمان — بركاء 5",
      fr: "Usine de dessalement d'Oman — Barka 5",
    },
    organization: {
      en: "Oman Power & Water Procurement — Oman",
      ar: "شراء الطاقة والمياه — عمان",
      fr: "Approvisionnement en énergie et eau d'Oman — Oman",
    },
    country: "Oman",
    countryCode: "OM",
    sector: "water",
    budget: 28000000,
    currency: "OMR",
    deadline: "2026-05-20",
    publishDate: "2026-02-15",
    status: "open",
    description: {
      en: "Design, build, and operate a 300,000 m³/day reverse osmosis desalination plant at Barka. Includes intake and outfall systems, energy recovery devices, and a 25-year operation and maintenance contract.",
      ar: "تصميم وبناء وتشغيل محطة تحلية مياه بالتناضح العكسي بطاقة 300,000 م³/يوم في بركاء.",
      fr: "Conception, construction et exploitation d'une usine de dessalement par osmose inverse de 300 000 m³/jour à Barka.",
    },
    requirements: ["Desalination experience", "DBO contract experience", "Environmental compliance", "O&M capability"],
    matchScore: 52,
  },
  {
    id: "TND-2026-010",
    title: {
      en: "Jordan Telecom Authority — 5G Network Rollout",
      ar: "هيئة الاتصالات الأردنية — نشر شبكة 5G",
      fr: "Autorité des Télécoms de Jordanie — Déploiement du réseau 5G",
    },
    organization: {
      en: "Telecommunications Regulatory Commission — Jordan",
      ar: "هيئة تنظيم قطاع الاتصالات — الأردن",
      fr: "Commission de régulation des télécommunications — Jordanie",
    },
    country: "Jordan",
    countryCode: "JO",
    sector: "telecom",
    budget: 40000000,
    currency: "JOD",
    deadline: "2026-04-10",
    publishDate: "2026-02-25",
    status: "closing-soon",
    description: {
      en: "National 5G network infrastructure rollout across major Jordanian cities. Includes tower construction, antenna installation, core network equipment, and spectrum management systems. Phase 1 covers Amman, Zarqa, and Irbid.",
      ar: "نشر البنية التحتية لشبكة 5G الوطنية عبر المدن الأردنية الرئيسية. يشمل بناء الأبراج وتركيب الهوائيات ومعدات الشبكة الأساسية.",
      fr: "Déploiement de l'infrastructure réseau 5G nationale dans les principales villes jordaniennes.",
    },
    requirements: ["5G deployment experience", "Telecom license", "Tower construction", "Spectrum expertise"],
    matchScore: 73,
  },
  {
    id: "TND-2026-011",
    title: {
      en: "Bahrain Defence Force — Cybersecurity Operations Center",
      ar: "قوة دفاع البحرين — مركز عمليات الأمن السيبراني",
      fr: "Force de défense de Bahreïn — Centre d'opérations de cybersécurité",
    },
    organization: {
      en: "Bahrain Defence Force — Bahrain",
      ar: "قوة دفاع البحرين — البحرين",
      fr: "Force de défense de Bahreïn — Bahreïn",
    },
    country: "Bahrain",
    countryCode: "BH",
    sector: "defense",
    budget: 8000000,
    currency: "BHD",
    deadline: "2026-04-05",
    publishDate: "2026-02-01",
    status: "closing-soon",
    description: {
      en: "Establishment of a state-of-the-art Security Operations Center (SOC) for the Bahrain Defence Force. Includes SIEM deployment, threat intelligence platform, incident response automation, and 24/7 monitoring capabilities.",
      ar: "إنشاء مركز عمليات أمنية متطور لقوة دفاع البحرين. يشمل نشر SIEM ومنصة استخبارات التهديدات وأتمتة الاستجابة للحوادث.",
      fr: "Établissement d'un Centre d'Opérations de Sécurité (SOC) de pointe pour la Force de défense de Bahreïn.",
    },
    requirements: ["Security clearance", "SOC experience", "SIEM expertise", "ISO 27001"],
    matchScore: 61,
  },
  {
    id: "TND-2026-012",
    title: {
      en: "Tunisia Smart Agriculture — Irrigation Modernization",
      ar: "الزراعة الذكية في تونس — تحديث الري",
      fr: "Agriculture intelligente en Tunisie — Modernisation de l'irrigation",
    },
    organization: {
      en: "Ministry of Agriculture — Tunisia",
      ar: "وزارة الزراعة — تونس",
      fr: "Ministère de l'Agriculture — Tunisie",
    },
    country: "Tunisia",
    countryCode: "TN",
    sector: "agriculture",
    budget: 15000000,
    currency: "TND",
    deadline: "2026-05-30",
    publishDate: "2026-03-07",
    status: "open",
    description: {
      en: "Implementation of smart irrigation systems across 50,000 hectares in central Tunisia. Includes IoT soil moisture sensors, weather station networks, AI-based water management platform, and farmer mobile application.",
      ar: "تنفيذ أنظمة ري ذكية عبر 50,000 هكتار في وسط تونس. يشمل مستشعرات رطوبة التربة ومحطات الطقس ومنصة إدارة المياه بالذكاء الاصطناعي.",
      fr: "Mise en œuvre de systèmes d'irrigation intelligents sur 50 000 hectares dans le centre de la Tunisie.",
    },
    requirements: ["Agritech experience", "IoT systems", "Water management", "Mobile development"],
    matchScore: 76,
  },
];
